name: Build and push Playground Docker image

on:
    push:
        branches:
            - main
        paths-ignore:
            - '.github/**'
            - '.editorconfig'
            - '.gitignore'
            - 'LICENSE'
            - 'README.md'
    repository_dispatch:
        types: [ deploy ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 60
        steps:
            - name: Clone Playground repo
              uses: actions/checkout@v4

            - name: Add short hash to env
              run: echo "SHA_SHORT=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  push: true
                  tags: spawnlang/playground:latest, spawnlang/playground:${{ env.SHA_SHORT }}
